version: '2.1'
services:
  booker:
    build: .
    container_name: booker
    environment:
      DB_DRIVER: postgres+psycopg2
      DB_HOST: "127.0.0.1"
      DB_PORT: 5432
      DB_USER: "booker"
      DB_PASSWORD: "booker"
      DB_DATABASE: "booker"
      HTTP_HOST: "0.0.0.0"
      HTTP_PORT: "8080"
      HTTP_PORT_HOST: "8080"
    command: >
      bash -c "pipenv run alembic upgrade head
      && pipenv run python . "
    ports:
      - '${HTTP_PORT_HOST}:${HTTP_PORT}'
    expose:
      - "${HTTP_PORT}"

